<?php

namespace Container4RXsmzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\TaskService' shared autowired service.
     *
     * @return \App\Service\TaskService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TaskService.php';

        return $container->services['App\\Service\\TaskService'] = new \App\Service\TaskService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
