<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKP36ANx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKP36ANx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKP36ANx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKP36ANx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKP36ANx\App_KernelDevDebugContainer([
    'container.build_hash' => 'KP36ANx',
    'container.build_id' => 'dcd03466',
    'container.build_time' => 1698938702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKP36ANx');
